---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "Rubber Duck Booking Tool API"
basePath: "/api/v1"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /ducks/:
    get:
      tags:
      - "default_controller"
      description: "Get the list of all ducks"
      operationId: "controllers.default_controller.ducks_get"
      parameters: []
      responses:
        200:
          description: "An object which contains metadata and an array of ducks"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "token"
    in: "header"
definitions: {}
